version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
  db:
    build:
        context: .
        dockerfile: Dockerfile.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alpine
      MYSQL_DATABASE: guanafarma
      MYSQL_USER: guanafarma
      MYSQL_PASSWORD: guanafarma
    ports:
        - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data: